# issues/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import IssueViewSet, TeamViewSet # Import both ViewSets

router = DefaultRouter()
router.register(r'issues', IssueViewSet, basename='issue') # This handles /api/issues/ and /api/issues/{id}/
router.register(r'teams', TeamViewSet, basename='team')   # This will handle /api/teams/ and /api/teams/{id}/

urlpatterns = [
    path('', include(router.urls)), # Include all URLs generated by the router
    # You might also have specific paths for custom actions if they are not part of the router
    # For example, if you want 'my_issues' to be /api/my_issues/ instead of /api/issues/my_issues/
    # path('my_issues/', IssueViewSet.as_view({'get': 'my_issues'}), name='my-issues'),
]