# Generated by Django 5.2.4 on 2025-07-30 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_assigned_to_alter_issue_owner_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_team',
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The user assigned to this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(help_text='The user who created this issue.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
